AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - tmp/*
    - bin/*
    - Gemfile
    - lib/snippets/**/*
    - vendor/**/*
    - data/**/*
    - db/schema.rb
    - db/migrate/*
    - test/dummy/**/*
    - lib/shipit-engine.rb
    - template.rb

Layout/LineLength:
  Exclude:
    - config/routes.rb
    - test/**/*
    - lib/tasks/teams.rake
    - app/models/shipit/commit_deployment.rb
    - app/models/shipit/commit_deployment_status.rb
    - app/serializers/shipit/task_serializer.rb
  Max: 120

Style/SymbolProc:
  Exclude:
    - app/models/shipit/*

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/serializers/**/*

Lint/RescueException:
  Exclude:
    - app/models/shipit/task_execution_strategy/default.rb

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

# This cop is broken https://github.com/rubocop-hq/rubocop/pull/7531
Layout/RescueEnsureAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
    Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

# Crashing cops. We need to update rubocop at some point but better do it in its own PR.
Layout/BlockAlignment:
  Exclude:
    - config/initializers/inflections.rb
    - config/routes.rb
    - lib/tasks/cron.rake
    - lib/tasks/dev.rake
    - lib/tasks/shipit.rake
    - lib/tasks/teams.rake
