Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - Gemfile
    - lib/snippets/**/*
    - vendor/**/*
    - data/**/*
    - db/schema.rb
    - db/migrate/*
    - test/dummy/**/*
    - lib/shipit-engine.rb
    - template.rb

inherit_from:
  .rubocop_todo.yml

Rails/FindEach:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Lint/RescueException:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - test/**/*
    - lib/tasks/teams.rake
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/serializers/**/*

Style/StringLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/GuardClause:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/Alias:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineHashBraceLayout:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false # totally broken

Layout/IndentHash:
  Enabled: false

Layout/IndentArray:
  Enabled: false # broken

Layout/ElseAlignment:
  Enabled: false # broken

Style/ParallelAssignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Performance/Casecmp:
  Enabled: false # ugly

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

Style/FrozenStringLiteralComment:
  Enabled: false
