AllCops:
  Exclude:
    - tmp/*
    - bin/*
    - Gemfile
    - lib/snippets/**/*
    - vendor/**/*
    - data/**/*
    - db/schema.rb
    - db/migrate/*
    - test/dummy/**/*
    - lib/shipit-engine.rb
    - template.rb

inherit_gem:
  rubocop-shopify: rubocop.yml

Layout/LineLength:
  Exclude:
    - config/routes.rb
    - test/**/*
    - lib/tasks/teams.rake
    - app/models/shipit/commit_deployment.rb
    - app/models/shipit/commit_deployment_status.rb
    - app/serializers/shipit/task_serializer.rb
  Max: 120

Style/SymbolProc:
  Exclude:
    - app/models/shipit/*

Style/PerlBackrefs:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - app/serializers/**/*

Lint/RescueException:
  Exclude:
    - app/models/shipit/task_execution_strategy/default.rb

Lint/MissingCopEnableDirective:
  Exclude:
    - 'lib/shipit/stack_commands.rb'
    - 'lib/shipit/task_commands.rb'

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

# This cop is broken https://github.com/rubocop-hq/rubocop/pull/7531
Layout/RescueEnsureAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassMethodsDefinitions:
  Exclude:
    - 'app/models/shipit/commit.rb'
    - 'app/models/shipit/deploy.rb'
    - 'app/models/shipit/merge_request.rb'
    - 'app/models/shipit/repository.rb'
    - 'app/models/shipit/review_stack.rb'
    - 'app/models/shipit/review_stack_provisioning_queue.rb'
    - 'app/models/shipit/stack.rb'
    - 'app/models/shipit/task.rb'
    - 'app/models/shipit/user.rb'
    - 'app/models/shipit/webhooks/handlers/handler.rb'
    - 'lib/shipit/simple_message_verifier.rb'
    - 'test/models/shipit/stack_test.rb'
    - 'test/unit/shipit_deployment_checks_test.rb'

Style/OpenStructUse:
  Exclude:
    - 'test/jobs/update_github_last_deployed_ref_job_test.rb'
    - 'test/models/commits_test.rb'
    - 'test/models/shipit/check_run_test.rb'
    - 'test/models/shipit/webhooks/handlers/pull_request/review_stack_adapter_test.rb'
    - 'test/models/status_test.rb'
    - 'test/unit/github_app_test.rb'
    - 'test/unit/github_apps_test.rb'

Naming/InclusiveLanguage:
  Enabled: false
