Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - bin/*
    - Gemfile
    - lib/snippets/**/*
    - vendor/**/*
    - data/**/*
    - db/schema.rb
    - db/migrate/*
    - test/dummy/**/*
    - lib/shipit-engine.rb

inherit_from:
  .rubocop_todo.yml

Rails/FindEach:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Lint/RescueException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/Next:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - test/**/*
    - lib/tasks/teams.rake
  Max: 120

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 35

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/IndentHash:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Style/PredicateName:
  Exclude:
    - app/serializers/**/*

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/StringLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrivialAccessors:
  AllowPredicates: true

Style/ExtraSpacing:
  AllowForAlignment: false

Style/GuardClause:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/Alias:
  Enabled: false

Style/MultilineHashBraceLayout:
  Enabled: false

Style/IndentationWidth:
  Enabled: false # totally broken

Style/IndentArray:
  Enabled: false # broken

Style/ElseAlignment:
  Enabled: false # broken

Style/ParallelAssignment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
