ApplicationMetrics.register_metric(:counter, :shipit_predictive_branch_count, [:pipeline, :stack, :status], 'Count predictive branches')
ApplicationMetrics.register_metric(:counter, :shipit_predictive_branch_duration_seconds_sum, [:pipeline, :stack, :status], 'Summarize predictive branches durations in seconds')
ApplicationMetrics.register_metric(:counter, :shipit_predictive_build_count, [:pipeline, :status], 'Count predictive builds')
ApplicationMetrics.register_metric(:counter, :shipit_predictive_build_duration_seconds_sum, [:pipeline, :status], 'Summarize predictive builds durations in seconds')
ApplicationMetrics.register_metric(:counter, :shipit_task_count, [:pipeline, :stack, :type, :status, :executor], 'Count tasks')
ApplicationMetrics.register_metric(:counter, :shipit_task_duration_seconds_sum, [:pipeline, :stack, :type, :status, :executor], 'Summarize tasks durations')
ApplicationMetrics.register_metric(:counter, :merge_requests_count, [:pipeline, :stack, :mode, :status], 'Count processed PRs')
ApplicationMetrics.register_metric(:counter, :merge_requests_duration_seconds_sum, [:pipeline, :stack, :mode, :status],  'Summarize processed PRs durations')
ApplicationMetrics.register_metric(:gauge, :merge_requests_gauge, [:pipeline, :stack],  'PRs Queue Gauge')
ApplicationMetrics.register_metric(:gauge, :cd_sequential_failures, [:pipeline, :stack],  'CD Sequential Failures')