#!/usr/bin/env python

import sys
import setuptools

def print_version(*args, **kwargs):
    print(kwargs['version'])

setuptools.setup = print_version

if __name__ == '__main__':
    execfile(sys.argv[1])
