#!/usr/bin/env bash
# 
# HEROKU_APP=$1
# 
# if [ -z $HEROKU_APP ]; then
#   echo "Usage: $0 <app-name>" >&2
#   exit 1;
# fi
# 
# HEROKU_GIT="git@heroku.com:$HEROKU_APP.git"
# 
# REMOTES=`git ls-remote --heads $HEROKU_GIT 2> /dev/null`;
# RET=$?
# 
# test 0 -eq $RET || exit $RET
# 
# echo $REMOTES | grep 'refs/heads/master' | awk '{ print $1; }'
