#!/usr/bin/env bash

HEROKU_APP=$1

if [ -z $HEROKU_APP ]; then
  echo "Usage: $0 <app-name>"
  exit 1;
fi

HEROKU_GIT="git@heroku.com:$HEROKU_APP.git"
HEROKU_RELEASE=`git ls-remote --heads $HEROKU_GIT 2>&1 | grep 'refs/heads/master' | awk '{ print $1; }'`
echo $HEROKU_RELEASE
