#!/usr/bin/env bash

echo -e "\033[1;31mpublishConfig setting in your package.json is misconfigured.\033[0m"
echo -e "\033[1;31mSee documentation: https://development.shopify.io/guides/gems/\033[0m"
exit 1
