#!/usr/bin/env bash

echo -e "\033[1;31m Misconfigured package.json, please ensure the following has been met:\n \033[0m"

echo -e "\033[1;31m * Please add a publishConfig with an access setting in your package.json.  e.g.,\033[0m"
echo -e "\n\033[1;31m\t\"publishConfig:\" {\n\t   \"access\": \"<public|restricted>\" \n\t} \033[0m"
echo -e "\n\033[1;31m * If your package is private, ensure your the package name is scoped (@organization/package) \033[0m"
exit 1
