#!/usr/bin/env bash

function red() {
  echo -e "\033[0;31m$1\033[0m"
}
function green() {
  echo -e "\033[0;32m$1\033[0m"
}
function yellow() {
  echo -e "\033[0;33m$1\033[0m"
}

HEROKU_APP=$1
HEROKU_RELEASE=`heroku releases --app repodb 2>/dev/null | head -n2 | tail -n1 | cut -d" " -f1`

if [ -z $HEROKU_RELEASE ]; then
  red "Error detecting current heroku release."
  exit 1;
fi

green "Current heroku release: $HEROKU_RELEASE"

green "Pushing to heroku."
git push git@heroku.com:$HEROKU_APP.git $SHA:master
if [ $? -ne 0 ]; then
  red "Heroku push rejected. See message above."
  red "Please contact a heroku collaborator for $HEROKU_APP:"
  heroku sharing --app $HEROKU_APP
  exit 1;
fi

MIGRATIONS=`heroku run rake db:migrate:status --app $HEROKU_APP | grep -e '^\s*down'`

if [ "$MIGRATIONS" != "" ]; then
  green "There are pending migrations to apply:"
  echo $MIGRATIONS

  green "Migrating database."
  heroku run rake db:migrate --app $HEROKU_APP
  if [ $? -ne 0 ]; then
    red "Migration failed! This is bad."
    red "Please contact a heroku collaborator for $HEROKU_APP:"
    heroku sharing --app $HEROKU_APP
    red "The app $HEROKU_APP will now be reverted to its last working version $HEROKU_RELEASE."
    heroku releases:rollback $HEROKU_RELEASE --app $HEROKU_APP
    red "Abort."
    exit 1
  fi
else
  green "There are no pending migrations."
fi

green "All done."

