development:
  authentication: false
  # host: https://57212e00.ngrok.com
  # authentication:
  #   provider: google_apps
  #   gem: omniauth-google-apps
  #   options:
  #     domain: 'example.com'

  github: false

test:
  host: https://example.com
  authentication:
  github:
    key: 1d
    secret: s3cr37
