#!/usr/bin/env bash

# Output all commands, stop on failures
set -e
set -x

cp -n config/database.yml.example config/database.yml || true
cp -n config/secrets.yml.example config/secrets.yml || true
bundle install
bundle exec rake db:create db:schema:load
