#!/usr/bin/env ruby
# frozen_string_literal: true

trap('INT') do
  puts "Recieved SIGINT, aborting."
  exit 1
end

trap('TERM') do
  puts "Recieved SIGTERM, aborting."
  exit 1
end

puts "Sleeping for 10 seconds"
sleep(10)
puts "I wasn't killed? WTF"
