name: Release

on:
  workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    environment: release

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: ruby/setup-ruby@dffb23f65a78bba8db45d387d5ea1bbd6be3ef18
        with:
          bundler-cache: true

      - uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169
